use_frameworks!

platform :ios, '13.0'

target 'DTHReusableSource_Example' do
  pod 'DTHReusableSource', :path => '../'

  target 'DTHReusableSource_Tests' do
    inherit! :search_paths

    
  end
end
